services:
  ftp:
    build: ./bonus/ftp
    container_name: ftp
    ports:
      - "21:21"
      - "30000-30100:30000-30100"
    networks:
      - inception
    volumes:
      - wordpress_volume:/var/www
    env_file:
      - .env
  static_website:
    build: ./bonus/static_website
    container_name: static_website
    ports:
      - "8081:80"
    networks:
      - inception
    restart: always
  redis:
      build: ./bonus/redis
      container_name: redis
      networks:
        - inception
      restart: always
  adminer:
    build: ./bonus/adminer
    container_name: adminer
    networks:
      - inception
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
    restart: always
  portainer:
    container_name: portainer
    build: ./bonus/portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_volume:/data
    ports:
      - 9443:9443
    networks:
      - inception
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - mariadb_volume:/var/lib/mysql
    networks:
      - inception
    restart: always
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
      - redis
    env_file:
      - .env
    volumes:
      - wordpress_volume:/var/www
    networks:
      - inception
    restart: always
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress_volume:/var/www
    env_file:
      - .env
    networks:
      - inception
    restart: always

volumes:
  mariadb_volume:
    name: mariadb_data
    driver_opts:
      type: none
      o: bind
      device: /home/amarzaq/data/mariadb
  wordpress_volume:
    name: wordpress_data
    driver_opts:
      type: none
      o: bind
      device: /home/amarzaq/data/wordpress
  portainer_volume:
    name: portainer_data
    driver_opts:
      type: none
      o: bind
      device: /home/amarzaq/data/portainer

networks:
  inception:
    name: inception_network